### ISSUE TITLE
我是一个新手，可以用到 llama 上不

### ISSUE THREAD

**Issue by ze00ro** [X-jun-0130/LLM-Pretrain-FineTune#1]
我是一个AI菜鸟，
tencent pretrain 的代码没看懂，感觉老哥你的代码我能看懂
我想问这个可以用到 llama 上不？

谢谢

**Comment by X-jun-0130** [comment]
llama的话 你可以去transformers这个库里面看看支不支持llama，支持的话就改下from transformers import * 这部分
我印象中好像是支持的
