### ISSUE TITLE
预训练数据里的表格是怎么处理转换的？

### ISSUE THREAD

**Issue by chenryn** [X-jun-0130/LLM-Pretrain-FineTune#10]
看到 data 里有些期刊文章，里面有表格内容。表格数据转换成预训练语料应该是什么样子的呢？

看很多 LLM 输出都有markdown表格支持。这块是一整个表格变成一行 markdown 么？

**Comment by X-jun-0130** [comment]
对的  大模型里面涉及的表格格式  都变成了md格式
