### ISSUE TITLE
求预训练和sft的数据格式形式

### ISSUE THREAD

**Issue by cristianohello** [X-jun-0130/LLM-Pretrain-FineTune#11]

**Comment by X-jun-0130** [comment]
预训练数据格式：{“text”:“一条文本+模型结束符”}里面是自由文本

指令微调格式：单轮：{“text”:“User: 你好+模型结束符\n Assistant: 你好啊很高兴为你服务+模型结束符”}
                         多轮：{“text”:“User: 你好+模型结束符\n Assistant: 你好啊很高兴为你服务+模型结束符\n User: 你好+模型结束符 
                                     \n Assistant: 你好啊很高兴为你服务+模型结束符”}
注意指令微调里面的空格。
