### ISSUE TITLE
构建数据集

### ISSUE THREAD

**Issue by HarryFunn** [X-jun-0130/LLM-Pretrain-FineTune#12]
你好，想问一下对于一个专业领域类的数据集，我们应该如何去人工构造呢

**Comment by X-jun-0130** [comment]
首先考虑一些公开类的，开源高质量中英文数据、专业考试类试题

第二个人工+GPT4构建：  利用专业书籍、论文等高质量知识自己定义问题或者模型来生成问题，然后使用GPT4根据提供的书籍内容来抽取答案；数据形式多样，问题形式多样：纯文本、表格、json等

第三个纯人工，仿照上面第二个，利用人工抽取答案
