### ISSUE TITLE
数据去重逻辑

### ISSUE THREAD

**Issue by wandouguo** [X-jun-0130/LLM-Pretrain-FineTune#16]
在预训练阶段：包含书籍文档、百科、问答、对话等类型。各种类型间的去重逻辑

分类去重？交叉类别去重？
OR ，把所有数据都处理成max-length之后统一去重？

**Comment by X-jun-0130** [comment]
分类去重： 中英文进行分类，其他的中文之间进行整体去重。

分类去重完了之后，文本内部进行句子级别去重

**Comment by wandouguo** [comment]
> 分类去重： 中英文进行分类，其他的中文之间进行整体去重。
> 
> 分类去重完了之后，文本内部进行句子级别去重

去重 不考虑 文档类型吗，不同文档类型的长度差异很大；比如书籍和百科条目。谢谢

**Comment by X-jun-0130** [comment]
书籍等长篇幅 都会按照章进行切分的。

少部分类型差异比较大的 ，比如对话数据 和  一些文本数据   能够分开最好
