### ISSUE TITLE
请问微调模型的效果如何？

### ISSUE THREAD

**Issue by aiporter-1** [X-jun-0130/LLM-Pretrain-FineTune#2]
请问微调出来的模型有没有bad example或者不能回答的情况？ps 答案感觉回答的很机械

**Comment by X-jun-0130** [comment]
这个看指令数据集是什么质量了。
之前用chatglm跑出来的指令去微调，效果就成了那样。
后面用MOSS之类的医疗指令跑了下，说话效果好很多
