### ISSUE TITLE
Repo id must be in the form 'repo_name' or 'namespace/repo_name': './Model_TH/Bloom_6B4_zh/'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by SeekPoint** [X-jun-0130/LLM-Pretrain-FineTune#4]
(gh_LLM-Pretrain-FineTune) ub2004@ub2004-B85M-A0:~/llm_dev/LLM-Pretrain-FineTune$ deepspeed --master_addr 0.0.0.0 --master_port 6006 --include localhost:0 pretrain/Model_Bloom_Pretrain.py 
[2023-05-06 11:32:31,586] [WARNING] [runner.py:179:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-05-06 11:32:31,597] [INFO] [runner.py:508:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=6006 pretrain/Model_Bloom_Pretrain.py
[2023-05-06 11:32:33,107] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}
[2023-05-06 11:32:33,107] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-05-06 11:32:33,108] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-05-06 11:32:33,108] [INFO] [launch.py:162:main] dist_world_size=1
[2023-05-06 11:32:33,108] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ub2004/llm_dev/LLM-Pretrain-FineTune/Nlp_2023/Dialogue_Bloom/pretrain/Model_Bloom_Pretrain │
│ .py:14 in <module>                                                                               │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/home/ub2004/llm_dev/LLM-Pretrain-FineTune/Nlp_2023/Dialogue_Bloom/pretrain/Model_Bloom_Pretrai │
│ n.py'                                                                                            │
│                                                                                                  │
│ /home/ub2004/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py:64 │
│ 2 in from_pretrained                                                                             │
│                                                                                                  │
│   639 │   │   │   return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *input   │
│   640 │   │                                                                                      │
│   641 │   │   # Next, let's try to use the tokenizer_config file to get the tokenizer class.     │
│ ❱ 642 │   │   tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)   │
│   643 │   │   if "_commit_hash" in tokenizer_config:                                             │
│   644 │   │   │   kwargs["_commit_hash"] = tokenizer_config["_commit_hash"]                      │
│   645 │   │   config_tokenizer_class = tokenizer_config.get("tokenizer_class")                   │
│                                                                                                  │
│ /home/ub2004/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py:48 │
│ 6 in get_tokenizer_config                                                                        │
│                                                                                                  │
│   483 │   tokenizer_config = get_tokenizer_config("tokenizer-test")                              │
│   484 │   ```"""                                                                                 │
│   485 │   commit_hash = kwargs.get("_commit_hash", None)                                         │
│ ❱ 486 │   resolved_config_file = cached_file(                                                    │
│   487 │   │   pretrained_model_name_or_path,                                                     │
│   488 │   │   TOKENIZER_CONFIG_FILE,                                                             │
│   489 │   │   cache_dir=cache_dir,                                                               │
│                                                                                                  │
│ /home/ub2004/.local/lib/python3.8/site-packages/transformers/utils/hub.py:409 in cached_file     │
│                                                                                                  │
│    406 │   user_agent = http_user_agent(user_agent)                                              │
│    407 │   try:                                                                                  │
│    408 │   │   # Load from URL or cache if already cached                                        │
│ ❱  409 │   │   resolved_file = hf_hub_download(                                                  │
│    410 │   │   │   path_or_repo_id,                                                              │
│    411 │   │   │   filename,                                                                     │
│    412 │   │   │   subfolder=None if len(subfolder) == 0 else subfolder,                         │
│                                                                                                  │
│ /home/ub2004/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py:112 in      │
│ _inner_fn                                                                                        │
│                                                                                                  │
│   109 │   │   │   kwargs.items(),  # Kwargs values                                               │
│   110 │   │   ):                                                                                 │
│   111 │   │   │   if arg_name in ["repo_id", "from_id", "to_id"]:                                │
│ ❱ 112 │   │   │   │   validate_repo_id(arg_value)                                                │
│   113 │   │   │                                                                                  │
│   114 │   │   │   elif arg_name == "token" and arg_value is not None:                            │
│   115 │   │   │   │   has_token = True                                                           │
│                                                                                                  │
│ /home/ub2004/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py:160 in      │
│ validate_repo_id                                                                                 │
│                                                                                                  │
│   157 │   │   raise HFValidationError(f"Repo id must be a string, not {type(repo_id)}: '{repo_   │
│   158 │                                                                                          │
│   159 │   if repo_id.count("/") > 1:                                                             │
│ ❱ 160 │   │   raise HFValidationError(                                                           │
│   161 │   │   │   "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"            │
│   162 │   │   │   f" '{repo_id}'. Use `repo_type` argument if needed."                           │
│   163 │   │   )                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './Model_TH/Bloom_6B4_zh/'. Use `repo_type` argument if needed.
[2023-05-06 11:32:37,117] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 27332
[2023-05-06 11:32:37,118] [ERROR] [launch.py:324:sigkill_handler] ['/usr/bin/python3', '-u', 'pretrain/Model_Bloom_Pretrain.py', '--local_rank=0'] exits with return code = 1

**Comment by X-jun-0130** [comment]
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './Model_TH/Bloom_6B4_zh/'. Use `repo_type` argument if needed.

Bloom_6B4_zh是一个开源的模型，首先需要下载到本地，然后修改成对应的文件目录
