### ISSUE TITLE
替换成LLama : Error: Incorrect padding

### ISSUE THREAD

**Issue by SeekPoint** [X-jun-0130/LLM-Pretrain-FineTune#5]
#model_name = "/data-ssd-1t/hf_model/llama-7b-hf or llama-7b" -- Error: Incorrect padding
(base) ub2004@ub2004-B85M-A0:/data-ssd-1t/hf_model/llama-7b$ git remote -v
origin	https://huggingface.co/huggyllama/llama-7b (fetch)
origin	https://huggingface.co/huggyllama/llama-7b (push)
(base) ub2004@ub2004-B85M-A0:/data-ssd-1t/hf_model/llama-7b$ cd ../llama-7b-hf/
(base) ub2004@ub2004-B85M-A0:/data-ssd-1t/hf_model/llama-7b-hf$ git remote -v
origin	https://huggingface.co/decapoda-research/llama-7b-hf (fetch)
origin	https://huggingface.co/decapoda-research/llama-7b-hf (push)
(base) ub2004@ub2004-B85M-A0:/data-ssd-1t/hf_model/llama-7b-hf$

(gh_LLM-Pretrain-FineTune) ub2004@ub2004-B85M-A0:~/llm_dev/LLM-Pretrain-FineTune$ deepspeed --master_addr 0.0.0.0 --master_port 6006 --include localhost:0 pretrain/Model_Bloom_Pretrain.py
[2023-05-09 22:36:38,440] [WARNING] [runner.py:181:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-05-09 22:36:38,450] [INFO] [runner.py:527:main] cmd = /usr/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=6006 --enable_each_rank_log=None pretrain/Model_Bloom_Pretrain.py
[2023-05-09 22:36:39,921] [INFO] [launch.py:133:main] WORLD INFO DICT: {'localhost': [0]}
[2023-05-09 22:36:39,921] [INFO] [launch.py:139:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-05-09 22:36:39,921] [INFO] [launch.py:150:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-05-09 22:36:39,921] [INFO] [launch.py:151:main] dist_world_size=1
[2023-05-09 22:36:39,921] [INFO] [launch.py:153:main] Setting CUDA_VISIBLE_DEVICES=0
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ub2004/llm_dev/LLM-Pretrain-FineTune/Nlp_2023/Dialogue_Bloom/pretrain/Model_Bloom_Pretrain │
│ .py:15 in <module>                                                                               │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/home/ub2004/llm_dev/LLM-Pretrain-FineTune/Nlp_2023/Dialogue_Bloom/pretrain/Model_Bloom_Pretrai │
│ n.py'                                                                                            │
│ <string>:111 in __init__                                                                         │
│                                                                                                  │
│ /home/ub2004/.local/lib/python3.8/site-packages/transformers/training_args.py:1466 in            │
│ __post_init__                                                                                    │
│                                                                                                  │
│   1463 │   │   │                                                                                 │
│   1464 │   │   │   # will be used later by the Trainer                                           │
│   1465 │   │   │   # note: leave self.deepspeed unmodified in case a user relies on it not to b  │
│ ❱ 1466 │   │   │   self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)           │
│   1467 │   │   │   self.hf_deepspeed_config.trainer_config_process(self)                         │
│   1468 │   │                                                                                     │
│   1469 │   │   if self.push_to_hub_token is not None:                                            │
│                                                                                                  │
│ /home/ub2004/.local/lib/python3.8/site-packages/transformers/deepspeed.py:77 in __init__         │
│                                                                                                  │
│    74 │   """                                                                                    │
│    75 │                                                                                          │
│    76 │   def __init__(self, config_file_or_dict):                                               │
│ ❱  77 │   │   super().__init__(config_file_or_dict)                                              │
│    78 │   │   self._dtype = None                                                                 │
│    79 │   │   self.mismatches = []                                                               │
│    80                                                                                            │
│                                                                                                  │
│ /home/ub2004/.local/lib/python3.8/site-packages/transformers/deepspeed.py:67 in __init__         │
│                                                                                                  │
│    64 │   │   set_hf_deepspeed_config(self)                                                      │
│    65 │   │   dep_version_check("accelerate")                                                    │
│    66 │   │   dep_version_check("deepspeed")                                                     │
│ ❱  67 │   │   super().__init__(config_file_or_dict)                                              │
│    68                                                                                            │
│    69                                                                                            │
│    70 class HfTrainerDeepSpeedConfig(HfDeepSpeedConfig):                                         │
│                                                                                                  │
│ /home/ub2004/.local/lib/python3.8/site-packages/accelerate/utils/deepspeed.py:52 in __init__     │
│                                                                                                  │
│    49 │   │   │   │   config = json.load(f)                                                      │
│    50 │   │   else:                                                                              │
│    51 │   │   │   try:                                                                           │
│ ❱  52 │   │   │   │   config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("u   │
│    53 │   │   │   │   config = json.loads(config_decoded)                                        │
│    54 │   │   │   except (UnicodeDecodeError, AttributeError):                                   │
│    55 │   │   │   │   raise ValueError(                                                          │
│                                                                                                  │
│ /usr/lib/python3.8/base64.py:133 in urlsafe_b64decode                                            │
│                                                                                                  │
│   130 │   """                                                                                    │
│   131 │   s = _bytes_from_decode_data(s)                                                         │
│   132 │   s = s.translate(_urlsafe_decode_translation)                                           │
│ ❱ 133 │   return b64decode(s)                                                                    │
│   134                                                                                            │
│   135                                                                                            │
│   136                                                                                            │
│                                                                                                  │
│ /usr/lib/python3.8/base64.py:87 in b64decode                                                     │
│                                                                                                  │
│    84 │   │   s = s.translate(bytes.maketrans(altchars, b'+/'))                                  │
│    85 │   if validate and not re.fullmatch(b'[A-Za-z0-9+/]*={0,2}', s):                          │
│    86 │   │   raise binascii.Error('Non-base64 digit found')                                     │
│ ❱  87 │   return binascii.a2b_base64(s)                                                          │
│    88                                                                                            │
│    89                                                                                            │
│    90 def standard_b64encode(s):                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
Error: Incorrect padding
[2023-05-09 22:40:01,113] [INFO] [launch.py:297:sigkill_handler] Killing subprocess 10784
[2023-05-09 22:40:01,113] [ERROR] [launch.py:303:sigkill_handler] ['/usr/bin/python3', '-u', 'pretrain/Model_Bloom_Pretrain.py', '--local_rank=0'] exits with return code = 1

**Comment by SeekPoint** [comment]
got the same error with bloom-6b4-zh"


(gh_LLM-Pretrain-FineTune) ub2004@ub2004-B85M-A0:~/llm_dev/LLM-Pretrain-FineTune$ git diff
diff --git a/ds_config.json b/ds_config.json
index 2591a8b..f3bd14a 100644
--- a/ds_config.json
+++ b/ds_config.json
@@ -1,5 +1,5 @@
 {
-  "train_batch_size": 256,
+  "train_batch_size": 8,
 
     "optimizer": {
       "type": "Adam",
diff --git a/pretrain/Model_Bloom_Pretrain.py b/pretrain/Model_Bloom_Pretrain.py
index 9035b26..aaf78e5 100644
--- a/pretrain/Model_Bloom_Pretrain.py
+++ b/pretrain/Model_Bloom_Pretrain.py
@@ -8,7 +8,8 @@ from torch.utils.data import Dataset,random_split
 from transformers import AutoTokenizer, TrainingArguments, Trainer, AutoModelForCausalLM
 
 
-model_name = "./Model_TH/Bloom_6B4_zh/"
+#model_name = "/data-ssd-1t/hf_model/llama-7b-hf or llama-7b" -- Error: Incorrect padding
+model_name = "/data-ssd-1t/hf_model/bloom-6b4-zh"
 torch.manual_seed(42)
 
 tokenizer = AutoTokenizer.from_pretrained(model_name)
@@ -19,10 +20,10 @@ training_args = TrainingArguments(output_dir='./results',
                                  save_strategy='steps',
                                  save_steps = 6200,
                                  evaluation_strategy = 'epoch',
-                                 per_device_train_batch_size=32, 
-                                 per_device_eval_batch_size=32, 
+                                 per_device_train_batch_size=2, 
+                                 per_device_eval_batch_size=2, 
                                  lr_scheduler_type="cosine",
-                                 warmup_steps=500,
+                                 warmup_steps=50,
                                  weight_decay=0.01,
                                  fp16=True,
                                  gradient_checkpointing=True,

**Comment by X-jun-0130** [comment]
应该是与base64有关

**Comment by SeekPoint** [comment]
怎么解决呢？？？
