### ISSUE TITLE
请问预训练文本格式？

### ISSUE THREAD

**Issue by AceCHQ** [X-jun-0130/LLM-Pretrain-FineTune#6]
请问预训练的文本格式是否必须为<img width="105" alt="image" src="https://github.com/NLPxiaoxu/LLM-Pretrain-FineTune/assets/104981253/b012c7a8-620b-47a7-921c-86117152352b">。如果不是，会有什么影响吗？

**Comment by X-jun-0130** [comment]
这只是预训练的一个比较通用的开始和结束的符号标记。

如果是单纯的从初始化向量开始预训练模型，格式自己随意定。

但现在是基于别的底座进行的增量预训练，最好和其格式上保持一致。


还有一点，在生成的时候，模型推理的时候会从结束符那里自动停止，这个也是结束符的作用。
